### ISSUE TITLE
docuemntation says to use deploy, but deploy isn't a registered command

### ISSUE THREAD

**Issue by kshsapcpi** [whint/messagestore-viewer-cf#3]
Hi Team, As per the read me document we tried "docuemntation says to use deploy, but deploy isn't a registered command".Can you please advise to proceed further on this issue . Thank You . Sriram

**Comment by jmailaender** [comment]
Dear kshsapcpi,

many thanks for your comment.

Please make sure that you have installed the [Cloud Foundry CLI](https://github.com/cloudfoundry/cli/wiki/V7-CLI-Installation-Guide) before running the `deploy` command.

I've removed your *.docx attachment because is considered unsafe.

Best regards
David
